/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Converter: typeof import('./src/components/Converter/index.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Error: typeof import('./src/components/Error/index.vue')['default']
    ExchangeRates: typeof import('./src/components/ExchangeRates/index.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    Layout: typeof import('./src/components/App/Layout.vue')['default']
    Link: typeof import('./src/components/Layout/Nav/Link.vue')['default']
    Loader: typeof import('./src/components/Loader/index.vue')['default']
    Message: typeof import('primevue/message')['default']
    Nav: typeof import('./src/components/Layout/Nav/index.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Root: typeof import('./src/components/App/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Selector: typeof import('./src/components/Currency/Selector.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
